### ISSUE TITLE
Missing dependency for pandas

### ISSUE THREAD

**Issue by jeremyjordan** [MrPowers/levi#12]
This library doesn't currently have pandas listed as a dependency
https://github.com/MrPowers/levi/blob/main/pyproject.toml

However, it uses the `to_pandas()` method in `deltalake` which causes an error if you don't have `pandas` installed in your environment
https://github.com/MrPowers/levi/blob/main/levi/__init__.py#L49

**Comment by MrPowers** [comment]
@jeremyjordan - thanks for submitting this. Would you be willing to create a PR with a fix?

**Comment by jeremyjordan** [comment]
Sure thing!

**Comment by MrPowers** [comment]
@jeremyjordan - thanks for the contribution.  Any other suggested improvements / fixes, please let us know.  Really appreciate your feedback.

**Comment by jeremyjordan** [comment]
Thanks for putting together this library! It's simple and easy to use 😄 I'm really interested in things like #7 for monitoring Delta Tables.
